version: '3'

services:
  db:
    image: sqlite
    container_name: db
    volumes:
      - ./data/db:/usr/src/app/db
    restart: always

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
