# Generated by Django 5.0.4 on 2024-04-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ConfirmEmailToken',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
