# Generated by Django 5.0.4 on 2024-04-08 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_order_contact_order_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'Информация о продукте', 'verbose_name_plural': 'Информационный список о продуктах'},
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Внешний ИД'),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='model',
            field=models.CharField(blank=True, max_length=80, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_infos', to='backend.product', verbose_name='Продукт'),
        ),
        migrations.AddConstraint(
            model_name='productinfo',
            constraint=models.UniqueConstraint(fields=('product', 'shop', 'external_id'), name='unique_product_info'),
        ),
    ]
